"""empty message

Revision ID: 096c5a138e85
Revises: 
Create Date: 2024-01-19 12:27:36.389523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096c5a138e85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mysessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_mysessions_session_id_sessions')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessioncategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_sessioncategories_category_id_categories')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_sessioncategories_session_id_sessions')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessioncategories')
    op.drop_table('mysessions')
    op.drop_table('sessions')
    op.drop_table('categories')
    # ### end Alembic commands ###
