"""empty message

Revision ID: 18301de3ee0a
Revises: 8f77c74c5d69
Create Date: 2024-01-22 09:30:48.239142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18301de3ee0a'
down_revision = '8f77c74c5d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('text')

    # ### end Alembic commands ###
