"""correct misspellings

Revision ID: 8f77c74c5d69
Revises: e46b800865b7
Create Date: 2024-01-20 17:57:47.892670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f77c74c5d69'
down_revision = 'e46b800865b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('practitioner_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_sessions_practioner_id_practitioners', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_sessions_practitioner_id_practitioners'), 'practitioners', ['practitioner_id'], ['id'])
        batch_op.drop_column('practioner_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('practioner_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_sessions_practitioner_id_practitioners'), type_='foreignkey')
        batch_op.create_foreign_key('fk_sessions_practioner_id_practitioners', 'practitioners', ['practioner_id'], ['id'])
        batch_op.drop_column('practitioner_id')

    # ### end Alembic commands ###
